language: node_js
node_js:
  - '12'
services:
  - docker
install:
  - docker-compose --version
  - docker-compose build
  - docker-compose up -d postgres
  - docker-compose ps
script:
  - docker-compose run --rm app
