version: '2.4'
services:
  app:
    volumes:
      - './package.json:/hermes/package.json'
      - './src:/hermes/src'
      - './test:/hermes/test'
      - './yarn.lock:/hermes/yarn.lock'

  postgres:
    ports:
      - '5432:5432'
